### ISSUE TITLE
Error, Help

### ISSUE THREAD

**Issue by overfy** [NoNameSpecified/UnbelievaBoat-Python-Bot#1]
I got this error when starting the bot
```
Starting bot
Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Users\bimai\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 98, in on_ready
    check_status = await db_handler.check_json()
  File "D:\UnbelievaBoat\src\database\__init__.py", line 89, in check_json
    temp_json_content = json.load(temp_json_opening)
  File "C:\Users\bimai\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\bimai\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
n decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\bimai\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 4 column 25 (char 54)```

**Comment by overfy** [comment]
How to access the Roles shop ? and i found a lot of Internal Error, call admin. :((
